Refactor log generation steps in pipeline.yml

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -13,19 +13,19 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      steps:
-        - name: Generate logs
-          run: |
-            mkdir -p logs
+    steps:
+      - name: Generate logs
+        run: |
+          mkdir -p logs
       
-            echo "Starting pipeline..." > logs/pipeline.log
-            echo "Docker build failed ..." >> logs/pipeline.log
+          echo "Starting pipeline..." > logs/pipeline.log
+          echo "Docker build failed ..." >> logs/pipeline.log
       
-            exit 1
+          exit 1
 
-        - name: Upload logs
-          if: always()
-          uses: actions/upload-artifact@v4
-          with:
-            name: pipeline-logs
-            path: logs/pipeline.log
+      - name: Upload logs
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: pipeline-logs
+          path: logs/pipeline.log
